// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mBow7e_u2uJT7cp2P_gArsk15zvD-Zk',
    appId: '1:435931294039:web:730c97cdd5ab60f02df612',
    messagingSenderId: '435931294039',
    projectId: 'task-management-apps-ccbd1',
    authDomain: 'task-management-apps-ccbd1.firebaseapp.com',
    storageBucket: 'task-management-apps-ccbd1.appspot.com',
    measurementId: 'G-QXFP75GFNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUpViqvzmU1XZvvx55pvRJtKorijR468c',
    appId: '1:435931294039:android:a06bc09b99d069a02df612',
    messagingSenderId: '435931294039',
    projectId: 'task-management-apps-ccbd1',
    storageBucket: 'task-management-apps-ccbd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3LdKaNX7vFOUiNnaSZZFkol1RWvbA30',
    appId: '1:435931294039:ios:a8cda125b824ff362df612',
    messagingSenderId: '435931294039',
    projectId: 'task-management-apps-ccbd1',
    storageBucket: 'task-management-apps-ccbd1.appspot.com',
    androidClientId: '435931294039-0cmg30g7aj4evdvvc7sva1c10ppt5c6c.apps.googleusercontent.com',
    iosClientId: '435931294039-79uf4c6k4qjgecp8l1d5uq669n71g1s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG3LdKaNX7vFOUiNnaSZZFkol1RWvbA30',
    appId: '1:435931294039:ios:a8cda125b824ff362df612',
    messagingSenderId: '435931294039',
    projectId: 'task-management-apps-ccbd1',
    storageBucket: 'task-management-apps-ccbd1.appspot.com',
    androidClientId: '435931294039-0cmg30g7aj4evdvvc7sva1c10ppt5c6c.apps.googleusercontent.com',
    iosClientId: '435931294039-79uf4c6k4qjgecp8l1d5uq669n71g1s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
